### ISSUE TITLE
PipeFusion multi-node Error

### ISSUE THREAD

**Issue by feifeibear** [PipeFusion/PipeFusion#111]
+ torchrun --nproc_per_node=8 --nnodes=2 --node_rank 1 --master_addr 10.5.0.7 --master_port 6000 scripts/./pixart_example.py --model_id /data/fjr/PixArt-XL-2-1024-MS/ -p pipefusion --height 2048 --width 2048 --no_use_resolution_binning --pp_num_patch 16 --pipefusion_warmup_step 4
[2024-06-27 09:15:30,809] torch.distributed.run: [WARNING]
[2024-06-27 09:15:30,809] torch.distributed.run: [WARNING] *****************************************
[2024-06-27 09:15:30,809] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2024-06-27 09:15:30,809] torch.distributed.run: [WARNING] *****************************************
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']
Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']
Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']
INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']
                                                                INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB<?, ?it/s]
INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...:  20%|██        | 1/5 [00:00<00:0Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']       | 0/2 [00:00<?, ?it/s]
INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
                                                                Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']       | 0/2 [00:00<?, ?it/s]
Some weights of the model checkpoint were not used when initializing PixArtTransformer2DModel:
 ['caption_projection.y_embedding']
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
INFO 06-27 09:15:43 [distri_dit_pipefusion.py:51] Using pipeline parallelism, world_size: 16 and n_device_per_batch: 16
DistriPixArtAlphaPipeline from pretrain stage 1 0.0 GB
Loading pipeline components...:  20%|██        | 1/5 [00:00<00:00,  6.28it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...:  60%|██████    | 3/5 [00:00<00:0Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.48s/it]it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.49s/it]s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.40s/it]s/it]
Loading pipeline components...:  60%|██████    | 3/5 [00:07<00:03,  1.89s/it]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.47s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.67s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.64s/it]s/it]
Loading pipeline components...:  20%|██        | 1/5 [00:07<00:29,  7.34s/it]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.47s/it]
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.43s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.41s/it]
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.44s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...:  40%|████      | 2/5 [00:07<00:09,  3.13s/it]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.53s/it]
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.55s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.65s/it]
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.54s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.70s/it]
Loading pipeline components...: 100%|██████████| 5/5 [00:07<00:00,  1.55s/it]
DistriPixArtAlphaPipeline from pretrain stage 2 11.83976448 GB
DistriPixArtAlphaPipeline from pretrain stage 2 11.841435648 GB
DistriPixArtAlphaPipeline from pretrain stage 2 11.841435648 GB
  0%|          | 0/6 [00:00<?, ?it/s]DistriPixArtAlphaPipeline from pretrain stage 2 11.841435648 GB
  0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 226, in <module>
    main()
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 140, in main
    pipeline = DistriPixArtAlphaPipeline.from_pretrained(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 126, in from_pretrained
    ret = DistriPixArtAlphaPipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 57, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 179, in prepare
    self.pipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pip/distri_pixartalpha.py", line 362, in __call__
    self.comm_manager.irecv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 314, in irecv_from_prev
    self.first_recv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 272, in first_recv_from_prev
    self.recv_shape = self.recv_shape_comm()
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 233, in recv_shape_comm
    dist.recv(dim, src=self.prev_rank, group=self.extra_group if is_extra else None)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1804, in recv
    pg.recv([tensor], src, tag).wait()
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1961, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.19.4
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
Last error:
socketStartConnect: Connect to 10.5.0.11<44589> failed : Software caused connection abort
  0%|          | 0/6 [00:00<?, ?it/s]DistriPixArtAlphaPipeline from pretrain stage 2 11.83976448 GB
  0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 226, in <module>
    main()
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 140, in main
    pipeline = DistriPixArtAlphaPipeline.from_pretrained(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 126, in from_pretrained
    ret = DistriPixArtAlphaPipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 57, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 179, in prepare
    self.pipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pip/distri_pixartalpha.py", line 362, in __call__
    self.comm_manager.irecv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 314, in irecv_from_prev
    self.first_recv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 272, in first_recv_from_prev
    self.recv_shape = self.recv_shape_comm()
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 233, in recv_shape_comm
    dist.recv(dim, src=self.prev_rank, group=self.extra_group if is_extra else None)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1804, in recv
    pg.recv([tensor], src, tag).wait()
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1961, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.19.4
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
Last error:
socketStartConnect: Connect to 10.5.0.11<59809> failed : Software caused connection abort
  0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 226, in <module>
    main()
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 140, in main
    pipeline = DistriPixArtAlphaPipeline.from_pretrained(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 126, in from_pretrained
    ret = DistriPixArtAlphaPipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 57, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 179, in prepare
    self.pipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pip/distri_pixartalpha.py", line 362, in __call__
    self.comm_manager.irecv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 314, in irecv_from_prev
    self.first_recv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 272, in first_recv_from_prev
    self.recv_shape = self.recv_shape_comm()
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 233, in recv_shape_comm
    dist.recv(dim, src=self.prev_rank, group=self.extra_group if is_extra else None)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1804, in recv
    pg.recv([tensor], src, tag).wait()
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1961, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.19.4
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
Last error:
socketStartConnect: Connect to 10.5.0.11<59431> failed : Software caused connection abort
DistriPixArtAlphaPipeline from pretrain stage 2 11.83976448 GB
DistriPixArtAlphaPipeline from pretrain stage 2 11.743849472 GB
  0%|          | 0/6 [00:00<?, ?it/s]DistriPixArtAlphaPipeline from pretrain stage 2 11.83976448 GB
  0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 226, in <module>
    main()
  File "/data/fjr/PipeFusion/scripts/./pixart_example.py", line 140, in main
    pipeline = DistriPixArtAlphaPipeline.from_pretrained(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 126, in from_pretrained
    ret = DistriPixArtAlphaPipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 57, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pixartalpha.py", line 179, in prepare
    self.pipeline(
  File "/data/fjr/PipeFusion/pipefuser/pipelines/pip/distri_pixartalpha.py", line 362, in __call__
    self.comm_manager.irecv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 314, in irecv_from_prev
    self.first_recv_from_prev(dtype)
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 272, in first_recv_from_prev
    self.recv_shape = self.recv_shape_comm()
  File "/data/fjr/PipeFusion/pipefuser/utils.py", line 233, in recv_shape_comm
    dist.recv(dim, src=self.prev_rank, group=self.extra_group if is_extra else None)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1804, in recv
    pg.recv([tensor], src, tag).wait()
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1961, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.19.4
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
Last error:
socketStartConnect: Connect to 10.5.0.11<33359> failed : Software caused connection abort
  0%|          | 0/6 [00:00<?, ?it/s][2024-06-27 09:15:55,841] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62833 closing signal SIGTERM
[2024-06-27 09:15:55,843] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62834 closing signal SIGTERM
[2024-06-27 09:15:55,843] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62835 closing signal SIGTERM
[2024-06-27 09:15:55,844] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62836 closing signal SIGTERM
[2024-06-27 09:15:55,845] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62838 closing signal SIGTERM
[2024-06-27 09:15:55,863] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62839 closing signal SIGTERM
[2024-06-27 09:15:55,864] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 62840 closing signal SIGTERM
[2024-06-27 09:15:56,301] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 4 (pid: 62837) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
scripts/./pixart_example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-27_09:15:55
  host      : localhost.localdomain
  rank      : 12 (local_rank: 4)
  exitcode  : 1 (pid: 62837)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by feifeibear** [comment]
fix this bug with dist.barrier()

**Comment by lonngxiang** [comment]
> fix this bug with dist.barrier()

how to use?

**Comment by feifeibear** [comment]
> > fix this bug with dist.barrier()
> 
> how to use?

Please refer to readme. The script to run example is here.

examples/run.sh

**Comment by Funny-Boy-Max** [comment]
Hello, could you please provide me with your “pip list” environment? I'm currently setting up a distributed training scenario and keep running into library version compatibility issues.
